// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

package types

// Pointer is an opaque reference that satisfies all interfaces in this package.
type Pointer uintptr

// Pointer returns the underlying opaque pointer value.
func (p Pointer) Pointer() uintptr { return uintptr(p) }

// privateAnyObject implements the AnyObject interface.
func (p Pointer) privateAnyObject() {}

// privateCFType implements the CFType interface.
func (p Pointer) privateCFType() {}

// privateCFAllocator implements the CFAllocator interface.
func (p Pointer) privateCFAllocator() {}

// privateCFArray implements the CFArray interface.
func (p Pointer) privateCFArray() {}

// privateCFData implements the CFData interface.
func (p Pointer) privateCFData() {}

// privateCFDictionary implements the CFDictionary interface.
func (p Pointer) privateCFDictionary() {}

// privateCFMutableArray implements the CFMutableArray interface.
func (p Pointer) privateCFMutableArray() {}

// privateCFRunLoop implements the CFRunLoop interface.
func (p Pointer) privateCFRunLoop() {}

// privateCFString implements the CFString interface.
func (p Pointer) privateCFString() {}

// privateConstFSEventStreamRef implements the ConstFSEventStreamRef interface.
func (p Pointer) privateConstFSEventStreamRef() {}

// privateFSEventStreamRef implements the FSEventStreamRef interface.
func (p Pointer) privateFSEventStreamRef() {}

// AnyObject is an opaque reference to AnyObject type.
type AnyObject interface {
	Pointer() uintptr

	privateAnyObject()
}

// CFType is an opaque reference to CFType type.
type CFType interface {
	Pointer() uintptr

	privateCFType()
}

// CFAllocator is an opaque reference to CFAllocator type.
type CFAllocator interface {
	CFType

	privateCFAllocator()
}

// CFArray is an opaque reference to CFArray type.
type CFArray interface {
	AnyObject
	CFType

	privateCFArray()
}

// CFData is an opaque reference to CFData type.
type CFData interface {
	AnyObject
	CFType

	privateCFData()
}

// CFDictionary is an opaque reference to CFDictionary type.
type CFDictionary interface {
	AnyObject
	CFType

	privateCFDictionary()
}

// CFMutableArray is an opaque reference to CFMutableArray type.
type CFMutableArray interface {
	AnyObject
	CFArray

	privateCFMutableArray()
}

// CFRunLoop is an opaque reference to CFRunLoop type.
type CFRunLoop interface {
	CFType

	privateCFRunLoop()
}

// CFString is an opaque reference to CFString type.
type CFString interface {
	AnyObject
	CFType

	privateCFString()
}

// ConstFSEventStreamRef is an opaque reference to ConstFSEventStreamRef type.
type ConstFSEventStreamRef interface {
	Pointer() uintptr

	privateConstFSEventStreamRef()
}

// FSEventStreamRef is an opaque reference to FSEventStreamRef type.
type FSEventStreamRef interface {
	ConstFSEventStreamRef

	privateFSEventStreamRef()
}
