// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

package fsevents

import (
	"unsafe"
)

const sizeofUintptr = unsafe.Sizeof(uintptr(0))

var extern_FSEventStreamCreate_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamCreate FSEventStreamCreate "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamCreate_trampoline()

var extern_FSEventStreamInvalidate_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamInvalidate FSEventStreamInvalidate "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamInvalidate_trampoline()

var extern_FSEventStreamRelease_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamRelease FSEventStreamRelease "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamRelease_trampoline()

var extern_FSEventStreamRetain_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamRetain FSEventStreamRetain "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamRetain_trampoline()

var extern_FSEventStreamScheduleWithRunLoop_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamScheduleWithRunLoop FSEventStreamScheduleWithRunLoop "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamScheduleWithRunLoop_trampoline()

var extern_FSEventStreamShow_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamShow FSEventStreamShow "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamShow_trampoline()

var extern_FSEventStreamStart_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamStart FSEventStreamStart "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamStart_trampoline()

var extern_FSEventStreamStop_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamStop FSEventStreamStop "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamStop_trampoline()

var extern_FSEventStreamUnscheduleFromRunLoop_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_FSEventStreamUnscheduleFromRunLoop FSEventStreamUnscheduleFromRunLoop "/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices"
func extern_FSEventStreamUnscheduleFromRunLoop_trampoline()
