// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

#include "go_asm.h"
#include "textflag.h"

GLOBL ·extern_FSEventStreamCreate_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamCreate_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamCreate_trampoline(SB)
TEXT ·extern_FSEventStreamCreate_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamCreate(SB)

GLOBL ·extern_FSEventStreamInvalidate_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamInvalidate_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamInvalidate_trampoline(SB)
TEXT ·extern_FSEventStreamInvalidate_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamInvalidate(SB)

GLOBL ·extern_FSEventStreamRelease_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamRelease_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamRelease_trampoline(SB)
TEXT ·extern_FSEventStreamRelease_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamRelease(SB)

GLOBL ·extern_FSEventStreamRetain_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamRetain_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamRetain_trampoline(SB)
TEXT ·extern_FSEventStreamRetain_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamRetain(SB)

GLOBL ·extern_FSEventStreamScheduleWithRunLoop_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamScheduleWithRunLoop_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamScheduleWithRunLoop_trampoline(SB)
TEXT ·extern_FSEventStreamScheduleWithRunLoop_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamScheduleWithRunLoop(SB)

GLOBL ·extern_FSEventStreamShow_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamShow_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamShow_trampoline(SB)
TEXT ·extern_FSEventStreamShow_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamShow(SB)

GLOBL ·extern_FSEventStreamStart_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamStart_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamStart_trampoline(SB)
TEXT ·extern_FSEventStreamStart_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamStart(SB)

GLOBL ·extern_FSEventStreamStop_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamStop_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamStop_trampoline(SB)
TEXT ·extern_FSEventStreamStop_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamStop(SB)

GLOBL ·extern_FSEventStreamUnscheduleFromRunLoop_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_FSEventStreamUnscheduleFromRunLoop_trampolineABI0(SB)/const_sizeofUintptr,$·extern_FSEventStreamUnscheduleFromRunLoop_trampoline(SB)
TEXT ·extern_FSEventStreamUnscheduleFromRunLoop_trampoline(SB),NOSPLIT,$0-0
	JMP extern_FSEventStreamUnscheduleFromRunLoop(SB)
