// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

package dyld

import (
	"unsafe"
)

const sizeofUintptr = unsafe.Sizeof(uintptr(0))

var extern_dladdr_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dladdr dladdr "/usr/lib/libSystem.B.dylib"
func extern_dladdr_trampoline()

var extern_dlclose_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dlclose dlclose "/usr/lib/libSystem.B.dylib"
func extern_dlclose_trampoline()

var extern_dlerror_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dlerror dlerror "/usr/lib/libSystem.B.dylib"
func extern_dlerror_trampoline()

var extern_dlopen_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dlopen dlopen "/usr/lib/libSystem.B.dylib"
func extern_dlopen_trampoline()

var extern_dlopen_preflight_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dlopen_preflight dlopen_preflight "/usr/lib/libSystem.B.dylib"
func extern_dlopen_preflight_trampoline()

var extern_dlsym_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_dlsym dlsym "/usr/lib/libSystem.B.dylib"
func extern_dlsym_trampoline()
