// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

#include "go_asm.h"
#include "textflag.h"

GLOBL ·extern_dladdr_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dladdr_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dladdr_trampoline(SB)
TEXT ·extern_dladdr_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dladdr(SB)

GLOBL ·extern_dlclose_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dlclose_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dlclose_trampoline(SB)
TEXT ·extern_dlclose_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dlclose(SB)

GLOBL ·extern_dlerror_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dlerror_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dlerror_trampoline(SB)
TEXT ·extern_dlerror_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dlerror(SB)

GLOBL ·extern_dlopen_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dlopen_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dlopen_trampoline(SB)
TEXT ·extern_dlopen_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dlopen(SB)

GLOBL ·extern_dlopen_preflight_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dlopen_preflight_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dlopen_preflight_trampoline(SB)
TEXT ·extern_dlopen_preflight_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dlopen_preflight(SB)

GLOBL ·extern_dlsym_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_dlsym_trampolineABI0(SB)/const_sizeofUintptr,$·extern_dlsym_trampoline(SB)
TEXT ·extern_dlsym_trampoline(SB),NOSPLIT,$0-0
	JMP extern_dlsym(SB)
