// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

#include "go_asm.h"
#include "textflag.h"

GLOBL ·extern_CFArrayAppendValue_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFArrayAppendValue_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFArrayAppendValue_trampoline(SB)
TEXT ·extern_CFArrayAppendValue_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFArrayAppendValue(SB)

GLOBL ·extern_CFArrayCreateMutable_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFArrayCreateMutable_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFArrayCreateMutable_trampoline(SB)
TEXT ·extern_CFArrayCreateMutable_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFArrayCreateMutable(SB)

GLOBL ·extern_CFCopyDescription_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFCopyDescription_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFCopyDescription_trampoline(SB)
TEXT ·extern_CFCopyDescription_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFCopyDescription(SB)

GLOBL ·extern_CFCopyTypeIDDescription_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFCopyTypeIDDescription_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFCopyTypeIDDescription_trampoline(SB)
TEXT ·extern_CFCopyTypeIDDescription_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFCopyTypeIDDescription(SB)

GLOBL ·extern_CFDataGetBytePtr_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFDataGetBytePtr_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFDataGetBytePtr_trampoline(SB)
TEXT ·extern_CFDataGetBytePtr_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFDataGetBytePtr(SB)

GLOBL ·extern_CFDataGetLength_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFDataGetLength_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFDataGetLength_trampoline(SB)
TEXT ·extern_CFDataGetLength_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFDataGetLength(SB)

GLOBL ·extern_CFEqual_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFEqual_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFEqual_trampoline(SB)
TEXT ·extern_CFEqual_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFEqual(SB)

GLOBL ·extern_CFGetAllocator_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFGetAllocator_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFGetAllocator_trampoline(SB)
TEXT ·extern_CFGetAllocator_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFGetAllocator(SB)

GLOBL ·extern_CFGetRetainCount_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFGetRetainCount_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFGetRetainCount_trampoline(SB)
TEXT ·extern_CFGetRetainCount_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFGetRetainCount(SB)

GLOBL ·extern_CFGetTypeID_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFGetTypeID_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFGetTypeID_trampoline(SB)
TEXT ·extern_CFGetTypeID_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFGetTypeID(SB)

GLOBL ·extern_CFHash_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFHash_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFHash_trampoline(SB)
TEXT ·extern_CFHash_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFHash(SB)

GLOBL ·extern_CFRelease_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRelease_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRelease_trampoline(SB)
TEXT ·extern_CFRelease_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRelease(SB)

GLOBL ·extern_CFRetain_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRetain_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRetain_trampoline(SB)
TEXT ·extern_CFRetain_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRetain(SB)

GLOBL ·extern_CFRunLoopGetCurrent_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRunLoopGetCurrent_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRunLoopGetCurrent_trampoline(SB)
TEXT ·extern_CFRunLoopGetCurrent_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRunLoopGetCurrent(SB)

GLOBL ·extern_CFRunLoopGetMain_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRunLoopGetMain_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRunLoopGetMain_trampoline(SB)
TEXT ·extern_CFRunLoopGetMain_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRunLoopGetMain(SB)

GLOBL ·extern_CFRunLoopRun_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRunLoopRun_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRunLoopRun_trampoline(SB)
TEXT ·extern_CFRunLoopRun_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRunLoopRun(SB)

GLOBL ·extern_CFRunLoopRunInMode_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRunLoopRunInMode_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRunLoopRunInMode_trampoline(SB)
TEXT ·extern_CFRunLoopRunInMode_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRunLoopRunInMode(SB)

GLOBL ·extern_CFRunLoopStop_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFRunLoopStop_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFRunLoopStop_trampoline(SB)
TEXT ·extern_CFRunLoopStop_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFRunLoopStop(SB)

GLOBL ·extern_CFShow_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFShow_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFShow_trampoline(SB)
TEXT ·extern_CFShow_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFShow(SB)

GLOBL ·extern_CFStringCreateArrayBySeparatingStrings_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFStringCreateArrayBySeparatingStrings_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFStringCreateArrayBySeparatingStrings_trampoline(SB)
TEXT ·extern_CFStringCreateArrayBySeparatingStrings_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFStringCreateArrayBySeparatingStrings(SB)

GLOBL ·extern_CFStringCreateExternalRepresentation_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFStringCreateExternalRepresentation_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFStringCreateExternalRepresentation_trampoline(SB)
TEXT ·extern_CFStringCreateExternalRepresentation_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFStringCreateExternalRepresentation(SB)

GLOBL ·extern_CFStringCreateWithBytes_trampolineABI0(SB),NOPTR|RODATA,$const_sizeofUintptr
DATA ·extern_CFStringCreateWithBytes_trampolineABI0(SB)/const_sizeofUintptr,$·extern_CFStringCreateWithBytes_trampoline(SB)
TEXT ·extern_CFStringCreateWithBytes_trampoline(SB),NOSPLIT,$0-0
	JMP extern_CFStringCreateWithBytes(SB)
