// Code generated by go run zgen.go. DO NOT EDIT.

//go:build darwin
// +build darwin

package corefoundation

import (
	"unsafe"
)

const sizeofUintptr = unsafe.Sizeof(uintptr(0))

var extern_CFArrayAppendValue_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFArrayAppendValue CFArrayAppendValue "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFArrayAppendValue_trampoline()

var extern_CFArrayCreateMutable_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFArrayCreateMutable CFArrayCreateMutable "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFArrayCreateMutable_trampoline()

var extern_CFCopyDescription_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFCopyDescription CFCopyDescription "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFCopyDescription_trampoline()

var extern_CFCopyTypeIDDescription_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFCopyTypeIDDescription CFCopyTypeIDDescription "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFCopyTypeIDDescription_trampoline()

var extern_CFDataGetBytePtr_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFDataGetBytePtr CFDataGetBytePtr "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFDataGetBytePtr_trampoline()

var extern_CFDataGetLength_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFDataGetLength CFDataGetLength "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFDataGetLength_trampoline()

var extern_CFEqual_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFEqual CFEqual "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFEqual_trampoline()

var extern_CFGetAllocator_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFGetAllocator CFGetAllocator "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFGetAllocator_trampoline()

var extern_CFGetRetainCount_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFGetRetainCount CFGetRetainCount "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFGetRetainCount_trampoline()

var extern_CFGetTypeID_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFGetTypeID CFGetTypeID "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFGetTypeID_trampoline()

var extern_CFHash_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFHash CFHash "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFHash_trampoline()

var extern_CFRelease_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRelease CFRelease "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRelease_trampoline()

var extern_CFRetain_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRetain CFRetain "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRetain_trampoline()

var extern_CFRunLoopGetCurrent_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRunLoopGetCurrent CFRunLoopGetCurrent "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRunLoopGetCurrent_trampoline()

var extern_CFRunLoopGetMain_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRunLoopGetMain CFRunLoopGetMain "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRunLoopGetMain_trampoline()

var extern_CFRunLoopRun_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRunLoopRun CFRunLoopRun "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRunLoopRun_trampoline()

var extern_CFRunLoopRunInMode_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRunLoopRunInMode CFRunLoopRunInMode "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRunLoopRunInMode_trampoline()

var extern_CFRunLoopStop_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFRunLoopStop CFRunLoopStop "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFRunLoopStop_trampoline()

var extern_CFShow_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFShow CFShow "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFShow_trampoline()

var extern_CFStringCreateArrayBySeparatingStrings_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFStringCreateArrayBySeparatingStrings CFStringCreateArrayBySeparatingStrings "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFStringCreateArrayBySeparatingStrings_trampoline()

var extern_CFStringCreateExternalRepresentation_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFStringCreateExternalRepresentation CFStringCreateExternalRepresentation "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFStringCreateExternalRepresentation_trampoline()

var extern_CFStringCreateWithBytes_trampolineABI0 uintptr

//go:cgo_import_dynamic extern_CFStringCreateWithBytes CFStringCreateWithBytes "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
func extern_CFStringCreateWithBytes_trampoline()
