name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18.x
      - name: Get Go cache paths
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up Go cache
        uses: actions/cache@v2.1.7
        with:
          key: golangci-lint-${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: golangci-lint-${{ runner.os }}-go-
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.0
      - name: Get golangci-lint cache path
        id: golangci-lint-cache-status
        run: |
          echo "::set-output name=dir::$(golangci-lint cache status | head -1 | sed 's/^Dir: //')"
      - name: Set up golangci-lint cache
        uses: actions/cache@v2.1.7
        with:
          key: golangci-lint-${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.mod') }}
          restore-keys: golangci-lint-${{ runner.os }}-golangci-lint-
          path: ${{ steps.golangci-lint-cache-status.outputs.dir }}
      - name: Run golangci-lint
        run: |
          golangci-lint run --out-format=github-actions -- \
            $(go work edit -json | jq -c -r '[.Use[].DiskPath] | map_values(. + "/...")[]')

  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18.x
      - name: Get Go cache paths
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up Go cache
        uses: actions/cache@v2.1.7
        with:
          key: go-mod-tidy-${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            go-mod-tidy-${{ runner.os }}-go-
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
      - name: Run go mod tidy
        run: eval "$(go list -m -f '(cd {{printf "%q" .Dir}} && go mod tidy)')"
      - name: Check git diff
        run: git diff --exit-code

  commitlint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v4.1.9
